//
// This code was generated by Enunciate.
// http://enunciate.codehaus.org/
//
#import <libxml/xmlwriter.h>
#import <libxml/xmlreader.h>
#import <Foundation/Foundation.h>
#import "enunciate_common.h"
#import "fsv1.h"

#ifndef DEBUG_ENUNCIATE
//turn off enunciate debugging.
#define DEBUG_ENUNCIATE 0
#endif


@class FSTEMPLEV1Temples;
@class FSTEMPLEV1Temple;
@class FSV1BasicProperty;
@class FSV1BasicError;
@class FSV1BasicElement;
@class FSTEMPLEV1TempleRootElement;


/**
 *  A list of temples.

 @author Rob Lyon

 */
@interface FSTEMPLEV1Temples : NSObject
{
  @private
    int _count;
    NSArray *_templeItems;
}

/**
 * the number of temples.
 */
- (int) count;

/**
 * the number of temples.
 */
- (void) setCount: (int) newCount;

/**
 * a list of temples.
 */
- (NSArray *) templeItems;

/**
 * a list of temples.
 */
- (void) setTempleItems: (NSArray *) newTempleItems;
@end /* interface FSTEMPLEV1Temples */

/**
 *  A temple.

 @author Rob Lyon

 */
@interface FSTEMPLEV1Temple : NSObject
{
  @private
    NSString *_code;
    NSString *_oldCode;
    NSString *_requestedCode;
    NSString *_name;
    long *_district;
    NSString *_location;
    NSString *_dedicationDate;
}

/**
 * the code of the temple.
 */
- (NSString *) code;

/**
 * the code of the temple.
 */
- (void) setCode: (NSString *) newCode;

/**
 * the old code of the temple.
 */
- (NSString *) oldCode;

/**
 * the old code of the temple.
 */
- (void) setOldCode: (NSString *) newOldCode;

/**
 * the requested code of the temple.
 */
- (NSString *) requestedCode;

/**
 * the requested code of the temple.
 */
- (void) setRequestedCode: (NSString *) newRequestedCode;

/**
 * the name of the temple.
 */
- (NSString *) name;

/**
 * the name of the temple.
 */
- (void) setName: (NSString *) newName;

/**
 * the district of the temple.
 */
- (long *) district;

/**
 * the district of the temple.
 */
- (void) setDistrict: (long *) newDistrict;

/**
 * the location of the temple.
 */
- (NSString *) location;

/**
 * the location of the temple.
 */
- (void) setLocation: (NSString *) newLocation;

/**
 * the dedication date of the temple.
 */
- (NSString *) dedicationDate;

/**
 * the dedication date of the temple.
 */
- (void) setDedicationDate: (NSString *) newDedicationDate;
@end /* interface FSTEMPLEV1Temple */


/**
 *  @author Rob Lyon

 */
@interface FSTEMPLEV1TempleRootElement : FSV1BasicElement <EnunciateXML>
{
  @private
    FSTEMPLEV1Temples *_temples;
}

/**
 * The temples.
 */
- (FSTEMPLEV1Temples *) temples;

/**
 * The temples.
 */
- (void) setTemples: (FSTEMPLEV1Temples *) newTemples;
@end /* interface FSTEMPLEV1TempleRootElement */
